# This is a sample build configuration for Other.
# Check our guides at https://confluence.atlassian.com/x/5Q4SMw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: atlassian/default-image:2

pipelines:
  branches:
         dev:
           - step:
              script:
               - cp sample.env .env
               - npm install
               - npm install -g gulp
               - cd frontend
               - npm install
               - cd ..
               - gulp --cwd ./
